# Generated by Django 5.2.1 on 2025-05-28 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employees',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('glpi_token', models.CharField(max_length=256)),
                ('glpi_name', models.CharField(max_length=128)),
                ('tg_id', models.CharField(max_length=128)),
                ('tg_name', models.CharField(max_length=256)),
                ('surname', models.CharField(max_length=128)),
                ('name', models.CharField(max_length=128)),
                ('patronymic', models.CharField(max_length=128)),
            ],
        ),
    ]
