# Generated by Django 5.2.1 on 2025-06-02 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notify_listener', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employees',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='employees',
            name='glpi_token',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
