# Generated by Django 5.2.1 on 2025-06-20 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notify_listener', '0002_employees_is_active_alter_employees_glpi_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employees',
            name='glpi_name',
            field=models.CharField(max_length=128, unique=True),
        ),
        migrations.AlterField(
            model_name='employees',
            name='tg_id',
            field=models.CharField(max_length=128, unique=True),
        ),
        migrations.AlterField(
            model_name='employees',
            name='tg_name',
            field=models.CharField(max_length=256, unique=True),
        ),
    ]
